
services:
  agile_config_admin:
    image: "kklldog/agile_config"
    ports:
      - "15000:5000"
    networks:
      - net0
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - adminConsole=true
      - nodes=agile_config_admin:5000,agile_config_node1:5000,agile_config_node2:5000
      - db:provider=mysql
      - db:conn= database=CodeIsBug.Admin.AgileConfig;server=119.91.250.14;User Id=root;password=Admin123@zgr;port=3306
  agile_config_node1:
    image: "kklldog/agile_config"
    ports:
      - "15001:5000"
    networks:
      - net0
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - db:provider=mysql
      - db:conn= database=CodeIsBug.Admin.AgileConfig;server=119.91.250.14;User Id=root;password=Admin123@zgr;port=3306
    depends_on:
      - agile_config_admin
  agile_config_node2:
    image: "kklldog/agile_config"
    ports:
      - "15002:5000"
    networks:
      - net0
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - db:provider=mysql
      - db:conn= database=CodeIsBug.Admin.AgileConfig;server=119.91.250.14;User Id=root;password=Admin123@zgr;port=3306
    depends_on:
      - agile_config_admin
networks:
  net0:
