version: '3.4'

services:
  codeisbug.admin.api:
    image: ${DOCKER_REGISTRY-}codeisbugadminapi
    container_name: codeisbug.admin.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: CodeIsBug.Admin.Api/Dockerfile
    ports:
      - "8099:80"
    links:
      - redis
      - mysql
    networks:
      - "net1"
    depends_on:
      - "redis"
      - "mysql"
  


